---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1"}

run:
  path: ./ci/tasks/build.sh
  dir: api-gateway

inputs:
  - name: api-gateway

outputs:
  - name: artifacts

