version: '2'
services:

    janus:
        image: quay.io/hellofresh/janus
        ports:
            - "8080:8080"
        environment:
            DEBUG: 'false'
            PORT: '8080'
            DATABASE_DSN: 'mongodb://mongodb:27017/janus'
            REDIS_DSN: 'redis://redis:6379'
            STATSD_DSN: 'statsd:8125'
            STATSD_PREFIX: 'janus-docker.'

    mongodb:
        image: mongo
        ports:
            - "27017:27017"

    redis:
        image: redis

    statsd:
        image: hopsoft/graphite-statsd
        ports:
          - "8010:80"
          - "2003:2003"
          - "8125:8125/udp"
          - "8126:8126"
